### ISSUE TITLE
TypeError Grav\Plugin\OrestbidaCookieConsentPlugin::escapeQuotes()

### ISSUE THREAD

**Issue by LB72** [pmoreno-rodriguez/grav-plugin-orestbida-cookie-consent#1]
Hello, 
since updating to version V2.0.X I get an error when the plugin is activated:

"Orestbida Cookie Consent v1.0.0" Work fine but
"Orestbida Cookie Consent v2.0.X"  Not....

TypeError
Grav\Plugin\OrestbidaCookieConsentPlugin::escapeQuotes(): Argument #1 ($text) must be of type string, null given, called in /var/www/grav-admin/cache/twig/a0/a03acf080d951b72aaa45a472c2248f8e784f67f73f3534a34e49525b39b51f9.php on line 201

Cache was cleared
Grav v1.7.48 - Admin v1.10.48

**Comment by pmoreno-rodriguez** [comment]
You can put the yaml file of the plugin in the /config/ folder

**Comment by LB72** [comment]
I'm not sure I understand. I have 2 files 
/var/www/grav-admin/user/XXXXX/config/plugins/orestbida-cookie-consent.yaml
/var/www/grav-admin/user/plugins/orestbida-cookie-consent/orestbida-cookie-consent.yaml

This one, /var/www/grav-admin/user/XXXXX/config/plugins/orestbida-cookie-consent.yaml, is created via the plugin admin interface.

**Comment by pmoreno-rodriguez** [comment]
All plugins when you save them, create a yaml file in **/var/www/grav-admin/user/config/plugins/**, In this case, **orestbida-cookie-consent.yaml**

**Comment by LB72** [comment]
Here the file content :

```enabled: true
cdn: true
theme: default
autoshow: true
show_delay: 3000
hideFromBots: false
disablePageInteraction: false
consent_layout: bar
consent_position: bottom_right
consent_title: Cookies...
consent_description: blabla
consent_acceptAllBtn: 'Accept All'
consent_acceptNecessaryBtn: 'Reject All'
consent_showPreferencesBtn: 'Manage Preferences'
consent_footer: null
preferences_layout: box
preferences_position: left
preferences_title: null
preferences_acceptAllBtn: 'Accept All'
preferences_acceptNecessaryBtn: 'Reject All'
preferences_savePreferencesBtn: 'Save Preferences'
cookies_sections:
  default: usage
  usage:
    title: 'Cookies Usage'
    description: blabla
  necessary:
    title: null
    description: null
  functionality:
    title: null
    description: null
  analytics:
    title: null
    description: null
  marketing:
    title: null
    description: null
  more_info:
    title: null
    description: null
categories:
  functionality: '0'
  analytics: '0'
  marketing: '0'
```

**Comment by pmoreno-rodriguez** [comment]
Ok. Can you try with the new code in the develop branch?. Only copy the [orestbida-cookie-consent.php](https://github.com/pmoreno-rodriguez/grav-plugin-orestbida-cookie-consent/blob/develop/orestbida-cookie-consent.php) to your plugin folder

**Comment by LB72** [comment]
Don't work :-(

```Grav\Framework\Session\Exceptions\SessionException thrown with message "Failed to start session: session_start(): Session cannot be started after headers have already been sent"

Stacktrace:
#10 Grav\Framework\Session\Exceptions\SessionException in /var/www/grav-admin/system/src/Grav/Framework/Session/Session.php:252
#9 Grav\Framework\Session\Session:start in /var/www/grav-admin/system/src/Grav/Common/Session.php:49
#8 Grav\Common\Session:init in /var/www/grav-admin/system/src/Grav/Common/Processors/InitializeProcessor.php:452
#7 Grav\Common\Processors\InitializeProcessor:initializeSession in /var/www/grav-admin/system/src/Grav/Common/Processors/InitializeProcessor.php:109
#6 Grav\Common\Processors\InitializeProcessor:process in /var/www/grav-admin/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#5 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/grav-admin/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#4 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/grav-admin/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php:40
#3 Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport:process in /var/www/grav-admin/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#2 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/grav-admin/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#1 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/grav-admin/system/src/Grav/Common/Grav.php:312
#0 Grav\Common\Grav:process in /var/www/grav-admin/index.php:47
```

**Comment by pmoreno-rodriguez** [comment]
This is my plugin configuration:
```
enabled: true
cdn: true
theme: default
autoshow: true
show_delay: 3000
hideFromBots: false
disablePageInteraction: false
consent_layout: box
consent_position: bottom_right
consent_title: Cookies...
consent_description: blabla
consent_acceptAllBtn: 'Aceptar todo'
consent_acceptNecessaryBtn: 'Rechazar todo'
consent_showPreferencesBtn: 'Gestionar preferencias'
consent_footer: null
preferences_layout: box
preferences_position: left
preferences_title: 'Configuración de cookies'
preferences_acceptAllBtn: null
preferences_acceptNecessaryBtn: null
preferences_savePreferencesBtn: null
cookies_sections:
  default: usage
  usage:
    title: null
    description: null
  necessary:
    title: null
    description: null
  functionality:
    title: null
    description: null
  analytics:
    title: null
    description: null
  marketing:
    title: null
    description: null
  more_info:
    title: null
    description: null
categories:
  functionality: '0'
  analytics: '0'
  marketing: '0'
```

And in this screenshot you can the result:

![Image](https://github.com/user-attachments/assets/b1ea7f1f-021e-48ee-bc00-91e395ed16f6)

Can you clear cache from Grav and form your browser?
