### ISSUE TITLE
Plugin not displayed on the website

### ISSUE THREAD

**Issue by Unblack** [pmoreno-rodriguez/grav-plugin-orestbida-cookie-consent#2]
Many Thanks for this Projekt and your Work!

Although the plugin is activated, it is not displayed on the website.
Do I have to adjust anything in the theme for this?
-Orestbida Cookie Consent v2.1.0
-Grav v1.7.48 - Admin v1.10.48
-PHP Version 8.3.14

**Comment by pmoreno-rodriguez** [comment]
Hello. It's not enough to simply install the plugin and have it active (this is the default state). You have to save the configuration so it generates the .yaml file in the user/config/plugins folder. This will force you to fill in required fields, without which the plugin won't work.

You can see an example on my website [https://pmdesign.dev/](https://pmdesign.dev/), it has a 3 second delay (which can also be configured in the plugin)

**Comment by Unblack** [comment]
I have read this in the instructions. Thank you.
Filled all the fields and saved.
I have installed it both manually and via the admin interface.
But.
The .yaml file is not created in the user/config/plugins folder. 
The .yaml file is in the folder user/mywebsitename/config/plugins

**Comment by pmoreno-rodriguez** [comment]
Sometimes a folder with the site name is generated inside `user` when the security token fails. Try copying the yaml file from the /user/yoursite/config/plugins folder to /user/config/plugins.

**Comment by Unblack** [comment]
It didn't work for me.
The simple other banner plugin works., https://github.com/naucon/grav-plugin-cookieconsent 
I will try an other site template.

**Comment by pmoreno-rodriguez** [comment]
Can you put the contents of the file `orestbida-cookie-consent.yaml` from the folder `user/config/plugins`?. 

If you have your website online, can you put the URL?

What theme are you using?

**Comment by Unblack** [comment]
> enabled: true
cdn: true
theme: default
autoshow: true
show_delay: 1000
hideFromBots: false
disablePageInteraction: false
consent_layout: box
consent_position: top_left
consent_title: 'Wir nutzen Cookies'
consent_description: 'Wir nutzen Cookies'
consent_acceptAllBtn: Akzeptieren
consent_acceptNecessaryBtn: Ablehen
consent_showPreferencesBtn: 'Einstellungen verwalten'
consent_footer: null
preferences_layout: box
preferences_position: left
preferences_title: null
preferences_acceptAllBtn: Akzeptieren
preferences_acceptNecessaryBtn: Ablehen
preferences_savePreferencesBtn: 'Einstellungen speichern'
cookies_sections:
  usage:
    title: 'Wir nutzen Cookies'
    description: null
  necessary:
    title: 'erforderliche Coockies'
    description: 'Diese Cookies werden verwendet.'
  functionality:
    title: 'Wir nutzen Cookies'
    description: null
  analytics:
    title: 'Wir nutzen Cookies'
    description: null
categories:
  functionality: '1'
  analytics: '0'
  marketing: '0'

**Comment by pmoreno-rodriguez** [comment]
HI. Using your data I can't replicate the issue. Some screenshots with your data in my website (on localhost):

![Image](https://github.com/user-attachments/assets/931e5719-7f4b-4132-8be7-9af469f9b032)

![Image](https://github.com/user-attachments/assets/29ebc75d-a519-4980-86bf-b8839311b7d8)

```
enabled: true
cdn: true
theme: default
autoshow: true
show_delay: 1000
hideFromBots: false
disablePageInteraction: false
consent_layout: box
consent_position: top_left
consent_title: 'Wir nutzen Cookies'
consent_description: 'Wir nutzen Cookies'
consent_acceptAllBtn: Akzeptieren
consent_acceptNecessaryBtn: Ablehen
consent_showPreferencesBtn: 'Einstellungen verwalten'
consent_footer: null
preferences_layout: box
preferences_position: left
preferences_title: null
preferences_acceptAllBtn: Akzeptieren
preferences_acceptNecessaryBtn: Ablehen
preferences_savePreferencesBtn: 'Einstellungen speichern'
cookies_sections:
  usage:
    title: 'Wir nutzen Cookies'
    description: null
  necessary:
    title: 'erforderliche Coockies'
    description: 'Diese Cookies werden verwendet.'
  functionality:
    title: 'Wir nutzen Cookies'
    description: null
  analytics:
    title: 'Wir nutzen Cookies'
    description: null
categories:
  functionality: '1'
  analytics: '0'
  marketing: '0'
```

What could you do next?
- Use the code inspector to check if your page is blocking the orestbida cookie-consent JavaScript library.
- Clear the entire site cache.
- Clear the site data in your web browser.

Please let me know if you find any errors caused by the plugin.
